# Generated by Django 3.1.2 on 2021-04-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='address1',
            field=models.CharField(blank=True, help_text='Insert only if different from organisation!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_extension',
            field=models.CharField(blank=True, db_column='addressExtension', max_length=255, null=True, verbose_name='Address extension'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='brussels',
            field=models.BooleanField(default=False, verbose_name='Brussels-based'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(blank=True, db_column='firstName', max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(db_column='cid', primary_key=True, serialize=False, verbose_name='Contact ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(blank=True, db_column='lastName', max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone (mobile)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mtime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone (landline)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postal',
            field=models.BooleanField(default=False, verbose_name='Receive paper mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pref_lang',
            field=models.ForeignKey(db_column='prefLang', default='en', on_delete=django.db.models.deletion.RESTRICT, to='contacts.language', verbose_name='Language preference'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ehea',
            field=models.BooleanField(default=False, verbose_name='EHEA member'),
        ),
        migrations.AlterField(
            model_name='country',
            name='eter',
            field=models.BooleanField(default=False, verbose_name='Covered by ETER'),
        ),
        migrations.AlterField(
            model_name='country',
            name='eu',
            field=models.BooleanField(default=False, verbose_name='EU member'),
        ),
        migrations.AlterField(
            model_name='country',
            name='infogram_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (for Infogram)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='ISO 2-letter code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ISO 3-letter code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='longname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Long name (English)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='longname_local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Long name (local language)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (local language)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='tableau_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (for Tableau)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='tldomain',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Top-level domain'),
        ),
        migrations.AlterField(
            model_name='country',
            name='typo3boxdata',
            field=models.IntegerField(blank=True, null=True, verbose_name='Typo3 data'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Language code'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.IntegerField(db_column='rid', primary_key=True, serialize=False, verbose_name='Role ID'),
        ),
    ]
