# Generated by Django 3.1.2 on 2021-10-03 19:31

from django.db import migrations
import uni_db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210418_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['lastname', 'firstname'], 'verbose_name': 'Person'},
        ),
        migrations.AlterModelOptions(
            name='contactorganisation',
            options={'ordering': ['function'], 'verbose_name': 'Contact person'},
        ),
        migrations.AlterModelOptions(
            name='deqarconnectpartner',
            options={'ordering': ['id'], 'verbose_name': 'DEQAR CONNECT partner'},
        ),
        migrations.AlterModelOptions(
            name='deqarpartner',
            options={'ordering': ['id'], 'verbose_name': 'DEQAR project partner'},
        ),
        migrations.AlterModelOptions(
            name='octopusaccount',
            options={'verbose_name': 'Financial account'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id'], 'verbose_name': 'Organisation type'},
        ),
        migrations.AlterField(
            model_name='deqarconnectpartner',
            name='type',
            field=uni_db.fields.EnumField(choices=[('Coordinator', 'Coordinator'), ('QAA', 'QAA'), ('ENIC-NARIC', 'ENIC-NARIC'), ('Associate', 'Associate'), ('Expert', 'Expert')]),
        ),
        migrations.AlterField(
            model_name='deqarpartner',
            name='type',
            field=uni_db.fields.EnumField(choices=[('Coordinator', 'Coordinator'), ('Stakeholder Partner', 'Stakeholder Partner'), ('QAA Partner', 'QAA Partner'), ('Research Centre', 'Research Centre'), ('Associate Partner', 'Associate Partner')]),
        ),
    ]
