# Generated by Django 3.1.2 on 2021-10-17 21:06

from django.db import migrations, models
import django.db.models.deletion
import uni_db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(db_column='mid', primary_key=True, serialize=False, verbose_name='member ID')),
                ('cat', uni_db.fields.EnumField(choices=[('FOU', 'Founding'), ('SOP', 'Social Partner'), ('GOV', 'Governmental'), ('OBS', 'Observer')], verbose_name='category')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='member')),
                ('formDate', models.DateField(blank=True, db_column='formDate', null=True, verbose_name='form date')),
                ('signatory', models.CharField(blank=True, max_length=255, null=True, verbose_name='form signatory')),
                ('function', models.CharField(blank=True, max_length=255, null=True, verbose_name="form signatory's function")),
                ('votes', models.IntegerField(blank=True, null=True, verbose_name='votes')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('organisation', models.OneToOneField(db_column='oid', on_delete=django.db.models.deletion.RESTRICT, to='contacts.organisation')),
            ],
            options={
                'verbose_name': 'EQAR Member',
                'db_table': 'member',
                'ordering': ['cat', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(db_column='iid', primary_key=True, serialize=False, verbose_name='invoice ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='membership fee')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('account', models.OneToOneField(db_column='oaid', on_delete=django.db.models.deletion.RESTRICT, to='contacts.octopusaccount', verbose_name='financial account')),
                ('member', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Member')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
