# Generated by Django 3.1.2 on 2020-10-13 20:31

from django.db import migrations, models
import django.db.models.deletion
import uni_db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(db_column='mid', primary_key=True, serialize=False)),
                ('cat', uni_db.fields.EnumField(choices=[('FOU', 'Founding'), ('SOP', 'Social Partner'), ('GOV', 'Governmental'), ('OBS', 'Observer')], default='FOU')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('form_date', models.DateField(blank=True, db_column='formDate', null=True)),
                ('signatory', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(db_column='oid', on_delete=django.db.models.deletion.RESTRICT, to='contacts.organisation')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(db_column='iid', primary_key=True, serialize=False)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(db_column='oaid', on_delete=django.db.models.deletion.RESTRICT, to='contacts.octopusaccount')),
                ('member', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
