# Generated by Django 3.1.2 on 2021-04-18 20:18

from django.db import migrations, models
import django.db.models.deletion
import uni_db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210418_2218'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['cat', 'name'], 'verbose_name': 'EQAR Member'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='account',
            field=models.OneToOneField(db_column='oaid', on_delete=django.db.models.deletion.RESTRICT, to='contacts.octopusaccount', verbose_name='Financial account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Membership fee'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(db_column='iid', primary_key=True, serialize=False, verbose_name='Invoice ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='member',
            field=models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mtime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cat',
            field=uni_db.fields.EnumField(choices=[('FOU', 'Founding'), ('SOP', 'Social Partner'), ('GOV', 'Governmental'), ('OBS', 'Observer')], default='FOU', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='member',
            name='form_date',
            field=models.DateField(blank=True, db_column='formDate', null=True, verbose_name='Form date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='function',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Form signatory's function"),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(db_column='mid', primary_key=True, serialize=False, verbose_name='Member ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mtime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='organisation',
            field=models.OneToOneField(db_column='oid', on_delete=django.db.models.deletion.RESTRICT, to='contacts.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='signatory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Form signatory'),
        ),
        migrations.AlterField(
            model_name='member',
            name='votes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Votes'),
        ),
    ]
