# Generated by Django 3.1.2 on 2021-10-03 19:31

from django.db import migrations
import uni_db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210418_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cat',
            field=uni_db.fields.EnumField(choices=[('FOU', 'Founding'), ('SOP', 'Social Partner'), ('GOV', 'Governmental'), ('OBS', 'Observer')], verbose_name='Category'),
        ),
    ]
