version: '3'

services:
  backend:
    build: api/
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_DB_PASS
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=eqar
      - DJANGO_DB_USER=eqar

  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
#      - ./mariadb:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_DATABASE=eqar
      - MARIADB_USER=eqar
      - MARIADB_PASSWORD=${DJANGO_DB_PASS}
      - MARIADB_ROOT_PASSWORD=${DJANGO_DB_PASS}

