services:

  backend:
    build: api/
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_HOSTNAME
      - DJANGO_DB_PASS
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=eqar
      - DJANGO_DB_USER=eqar
      - PORT=8000
      - DEQAR_BASE
      - DEQAR_TOKEN
    volumes:
      - staticfiles:/eqar_db/static

  db:
    image: mariadb:10
    volumes:
      - data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - MARIADB_DATABASE=eqar
      - MARIADB_USER=eqar
      - MARIADB_PASSWORD=${DJANGO_DB_PASS}
      - MARIADB_ROOT_PASSWORD=${DJANGO_DB_PASS}
      - MARIADB_AUTO_UPGRADE=1

  frontend:
    image: nginx
    ports:
      - "${HTTP_PORT:-8080}:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./frontend:/usr/share/nginx/html/frontend:ro
      - staticfiles:/usr/share/nginx/html/static:ro

  ldap:
    build: slapd/
    ports:
      - "${LDAP_PORT:-3389}:389"
    depends_on:
      - db
    command: /wait-for-it.sh db:3306 -- slapd -d ${SLAPD_DEBUG:-320}


volumes:
  staticfiles:
  data:

