# Generated by Django 3.1.2 on 2022-02-11 22:00

from django.db import migrations

def create_api_user(apps, schema_editor):
    """
    create a default (local) user to access the API externally
    """

    User = apps.get_model('auth', 'User')
    try:
        api_user = User.objects.get(username='_eqarweb')
    except (User.DoesNotExist):
        api_user = User(
            username='_eqarweb',
            email='no-reply@eqar.eu'
        )
        api_user.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_api_user)
    ]
