# Generated by Django 3.1.2 on 2021-10-03 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('sql', models.TextField(verbose_name='SQL code')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Shared')),
                ('underlying_table', models.CharField(blank=True, max_length=255, null=True, verbose_name='Underlying table')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Owned by')),
            ],
            options={
                'verbose_name': 'Raw query',
                'verbose_name_plural': 'Raw queries',
                'db_table': '_queries',
                'ordering': ['description'],
            },
        ),
    ]
