# Generated by Django 3.1.2 on 2021-10-03 19:31

from django.db import migrations, models
import uni_db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_remove_registeredagency_register_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyupdate',
            name='source',
            field=uni_db.fields.EnumField(choices=[('DEQAR', 'Reports in DEQAR'), ('form', 'Annual survey')]),
        ),
        migrations.AlterField(
            model_name='agencyupdate',
            name='type',
            field=uni_db.fields.EnumField(choices=[('institutional', 'Instituional reviews'), ('programme', 'Programme-level reviews'), ('joint programme', 'Joint programme reviews')]),
        ),
        migrations.AlterField(
            model_name='applicationclarification',
            name='type',
            field=uni_db.fields.EnumField(choices=[('Panel', 'Panel'), ('Coordinator', 'Coordinator'), ('Agency', 'Agency'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='applicationrole',
            name='role',
            field=uni_db.fields.EnumField(choices=[('Panel member', 'Panel member'), ('Panel chair', 'Panel chair'), ('Panel secretary', 'Panel secretary'), ('Coordinator', 'Coordinator'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='applications',
            name='stage',
            field=uni_db.fields.EnumField(choices=[('1. Eligibility check', '1. Eligibility check'), ('2. Waiting report', '2. Waiting report'), ('3. First consideration', '3. First consideration'), ('4. Waiting representation', '4. Waiting representation'), ('5. Second consideration', '5. Second consideration'), ('6. Waiting appeal', '6. Waiting appeal'), ('7. Appeal consideration', '7. Appeal consideration'), ('8. Completed', '8. Completed'), ('-- Withdrawn', '-- Withdrawn')]),
        ),
        migrations.AlterField(
            model_name='applications',
            name='submit_date',
            field=models.DateField(db_column='submitDate'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='type',
            field=uni_db.fields.EnumField(choices=[('Initial', 'Initial application for registration'), ('Renewal', 'Application for renewal of registration')]),
        ),
        migrations.AlterField(
            model_name='changereport',
            name='stage',
            field=uni_db.fields.EnumField(choices=[('1. Analysis by Secretariat', '1. Analysis by Secretariat'), ('2. Sent to rapporteurs', '2. Sent to rapporteurs'), ('3. Waiting RC consideration', '3. Waiting RC consideration'), ('4. Completed', '4. Completed')]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='stage',
            field=uni_db.fields.EnumField(choices=[('1. Analysis by Secretariat', '1. Analysis by Secretariat'), ('2. Sent to rapporteurs', '2. Sent to rapporteurs'), ('3. Waiting RC consideration', '3. Waiting RC consideration'), ('4. Completed', '4. Completed')]),
        ),
    ]
