# Generated by Django 3.1.2 on 2021-10-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='selectName',
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS new_application;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS update_application;"
        ),
        migrations.RemoveField(
            model_name='changereport',
            name='selectName',
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS new_changeReport;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS update_changeReport;"
        ),
        migrations.RemoveField(
            model_name='registeredagency',
            name='registerUrl',
        ),
    ]
