# Generated by Django 3.1.2 on 2021-10-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='selectName',
            field=models.CharField(editable=False, blank=True, db_column='selectName', max_length=255, null=True),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS new_application;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS update_application;"
        ),
        migrations.AlterField(
            model_name='changereport',
            name='selectName',
            field=models.CharField(editable=False, blank=True, db_column='selectName', max_length=255, null=True),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS new_changeReport;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS update_changeReport;"
        ),
        migrations.AlterField(
            model_name='registeredagency',
            name='registerUrl',
            field=models.CharField(editable=False, blank=True, db_column='registerUrl', max_length=255, null=True),
            preserve_default=False,
        ),
    ]
