# Generated by Django 3.1.2 on 2022-04-25 18:10

from django.db import migrations

def convert_web_contact(apps, schema_editor):
    ContactOrganisation = apps.get_model('contacts', 'contactorganisation')
    RegisteredAgency = apps.get_model('agencies', 'registeredagency')
    for agency in RegisteredAgency.objects.all():
        if agency.webContact:
            try:
                co = ContactOrganisation.objects.get(organisation=agency.organisation, contact=agency.webContact)
                co.onRegister = True
                co.save()
            except ContactOrganisation.DoesNotExist:
                ContactOrganisation.objects.create(organisation=agency.organisation, contact=agency.webContact, onRegister=True)


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_add_roles_interests_applications'),
        ('contacts', '0004_contactorganisation_onregister'),
    ]

    operations = [
        migrations.RunPython(convert_web_contact),
        migrations.RemoveField(
            model_name='registeredagency',
            name='webContact',
        ),
    ]
