# Generated by Django 3.1.2 on 2022-08-29 16:26

from django.db import migrations, models
import django.db.models.deletion
import uni_db.fields

class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_adjust_panel_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='review',
            field=uni_db.fields.EnumField(choices=[('Full', 'Full review'), ('Focused', 'Focused review'), ('Targeted', 'Targeted review')], default='Full', verbose_name='type of review'),
        ),
    ]
