# Generated by Django 3.1.2 on 2022-08-29 16:26

from django.db import migrations, models
import django.db.models.deletion
import uni_db.fields

def set_previous_applications(apps, schema_editor):
    Applications = apps.get_model('agencies', 'applications')
    for application in Applications.objects.filter(models.Q(type='Renewal') | models.Q(review='Focused')):
        application.previous = application.agency.applications_set.filter(id__lt=application.id).order_by('id').last()
        application.save()


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_add_review_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='inherit_2_1',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 2.1'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_2_2',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 2.2'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_2_3',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 2.3'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_2_4',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 2.4'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_2_5',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 2.5'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_2_6',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 2.6'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_2_7',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 2.7'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_3_1',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 3.1'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_3_2',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 3.2'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_3_3',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 3.3'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_3_4',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 3.4'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_3_5',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 3.5'),
        ),
        migrations.AddField(
            model_name='applications',
            name='inherit_3_6',
            field=models.BooleanField(default=False, verbose_name='inherit ESG 3.6'),
        ),
        migrations.AddField(
            model_name='applications',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='following', to='agencies.applications', verbose_name='previous application'),
        ),
        migrations.RunPython(set_previous_applications, migrations.RunPython.noop),
    ]
