# Generated by Django 3.1.2 on 2022-09-01 16:42

from django.db import migrations, models
import uni_db.fields
import uni_db.validators


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_previous_review_and_inherit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='panel_2_1',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.1 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_2_2',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.2 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_2_3',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.3 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_2_4',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.4 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_2_5',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.5 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_2_6',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.6 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_2_7',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.7 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_3_1',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.1 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_3_2',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.2 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_3_3',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.3 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_3_4',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.4 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_3_5',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.5 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='panel_3_6',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.6 panel'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_2_1',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.1 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_2_2',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.2 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_2_3',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.3 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_2_4',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.4 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_2_5',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.5 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_2_6',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.6 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_2_7',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.7 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_3_1',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.1 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_3_2',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.2 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_3_3',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.3 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_3_4',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.4 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_3_5',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.5 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rapp_3_6',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.6 rapporteurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_2_1',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.1 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_2_2',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.2 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_2_3',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.3 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_2_4',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.4 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_2_5',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.5 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_2_6',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.6 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_2_7',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 2.7 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_3_1',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.1 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_3_2',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.2 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_3_3',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.3 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_3_4',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.4 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_3_5',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.5 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rc_3_6',
            field=uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], null=True, verbose_name='ESG 3.6 RC'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='submitDate',
            field=models.DateField(db_column='submitDate', validators=[uni_db.validators.validate_date_in_past], verbose_name='submitted on'),
        ),
    ]
