# Generated by Django 3.1.2 on 2022-11-05 21:29

from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import uni_db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0009_rename_esg_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsgVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ESG version',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EsgStandard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agencies.esgversion')),
            ],
            options={
                'verbose_name': 'ESG standard',
                'ordering': ['-version__active', 'version__name', 'part', 'number'],
                'unique_together': {('version', 'part', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationStandard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='agencies.applications')),
                ('standard', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='agencies.esgstandard')),
                ('panel', uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Full compliance', 'Full compliance'), ('Substantial compliance', 'Substantial compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], editable=False, null=True)),
                ('rapporteurs', uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], editable=False, null=True)),
                ('rc', uni_db.fields.EnumField(blank=True, choices=[('Compliance', 'Compliance'), ('Partial compliance', 'Partial compliance'), ('Non-compliance', 'Non-compliance')], editable=False, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('decision', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
            options={
                'ordering': ['application', 'standard'],
                'unique_together': {('application', 'standard')},
            },
        ),
    ]
