# Generated by Django 3.1.2 on 2022-11-05 21:29

from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import uni_db.fields

def populate_esg(apps, schema_editor):
    """
    Loads ESG 2005 & 2015 titles into the new tables
    """

    EsgVersion = apps.get_model('agencies', 'EsgVersion')
    EsgStandard = apps.get_model('agencies', 'EsgStandard')

    esg2005 = EsgVersion.objects.create(name='ESG 2005', active=False)
    esg2015 = EsgVersion.objects.create(name='ESG 2015', active=True)

    EsgStandard.objects.create(version=esg2005, part='2', number='1', title='Use of internal quality assurance procedures')
    EsgStandard.objects.create(version=esg2005, part='2', number='2', title='Development of external quality assurance processes')
    EsgStandard.objects.create(version=esg2005, part='2', number='3', title='Criteria for decisions')
    EsgStandard.objects.create(version=esg2005, part='2', number='4', title='Processes fit for purpose')
    EsgStandard.objects.create(version=esg2005, part='2', number='5', title='Reporting')
    EsgStandard.objects.create(version=esg2005, part='2', number='6', title='Follow-up procedures')
    EsgStandard.objects.create(version=esg2005, part='2', number='7', title='Periodic reviews')
    EsgStandard.objects.create(version=esg2005, part='2', number='8', title='System-wide analyses')
    EsgStandard.objects.create(version=esg2005, part='3', number='1', title='Use of external quality assurance procedures for higher education')
    EsgStandard.objects.create(version=esg2005, part='3', number='2', title='Official status')
    EsgStandard.objects.create(version=esg2005, part='3', number='3', title='Activities')
    EsgStandard.objects.create(version=esg2005, part='3', number='4', title='Resources')
    EsgStandard.objects.create(version=esg2005, part='3', number='5', title='Mission statement')
    EsgStandard.objects.create(version=esg2005, part='3', number='6', title='Independence')
    EsgStandard.objects.create(version=esg2005, part='3', number='7', title='External quality assurance criteria and processes used by the agencies')
    EsgStandard.objects.create(version=esg2005, part='3', number='8', title='Accountability procedures')

    EsgStandard.objects.create(version=esg2015, part='2', number='1', title='Consideration of internal quality assurance')
    EsgStandard.objects.create(version=esg2015, part='2', number='2', title='Designing methodologies fit for purpose')
    EsgStandard.objects.create(version=esg2015, part='2', number='3', title='Implementing processes')
    EsgStandard.objects.create(version=esg2015, part='2', number='4', title='Peer-review experts')
    EsgStandard.objects.create(version=esg2015, part='2', number='5', title='Criteria for outcomes')
    EsgStandard.objects.create(version=esg2015, part='2', number='6', title='Reporting')
    EsgStandard.objects.create(version=esg2015, part='2', number='7', title='Complaints and appeals')
    EsgStandard.objects.create(version=esg2015, part='3', number='1', title='Activities, policy and processes for quality assurance')
    EsgStandard.objects.create(version=esg2015, part='3', number='2', title='Official status')
    EsgStandard.objects.create(version=esg2015, part='3', number='3', title='Independence')
    EsgStandard.objects.create(version=esg2015, part='3', number='4', title='Thematic analysis')
    EsgStandard.objects.create(version=esg2015, part='3', number='5', title='Resources')
    EsgStandard.objects.create(version=esg2015, part='3', number='6', title='Internal quality assurance and professional conduct')

def populate_application_standard(apps, schema_editor):
    """
    Initialises ApplicationStandard from compliance levels in Applications model, following
    the same logic as the Applications.save() method
    """
    Applications = apps.get_model('agencies', 'Applications')
    EsgVersion = apps.get_model('agencies', 'EsgVersion')
    ApplicationStandard = apps.get_model('agencies', 'ApplicationStandard')

    for application in Applications.objects.all():
        for esg in EsgVersion.objects.get(active=True).esgstandard_set.all():
            attribute_name = f'{esg.part}_{esg.number}'
            if getattr(application, f'panel_{attribute_name}') or getattr(application, f'rapp_{attribute_name}') or getattr(application, f'rc_{attribute_name}'):
                ApplicationStandard.objects.create(
                    application=application,
                    standard=esg,
                    panel=getattr(application, f'panel_{attribute_name}'),
                    rapporteurs=getattr(application, f'rapp_{attribute_name}'),
                    rc=getattr(application, f'rc_{attribute_name}')
                )


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_applicationstandard_esgstandard_esgversion'),
    ]

    operations = [
        migrations.RunPython(
            code=populate_esg,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=populate_application_standard,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
