# Generated by Django 3.1.2 on 2023-01-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0011_initialise_esg_applicationstandard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='teleconfDate',
        ),
        migrations.AddField(
            model_name='applications',
            name='sitevisitDate',
            field=models.DateField(blank=True, db_column='sitevisitDate', null=True, verbose_name='site-visit date'),
        ),
    ]
