# Generated by Django 3.1.2 on 2023-02-26 00:30

from django.db import migrations


def fix_withdrawn(apps, schema_editor):
    """
    fix result to withdrawn if empty
    """
    Applications = apps.get_model('agencies', 'Applications')
    Applications.objects.filter(stage='-- Withdrawn', result__isnull=True).update(result='Withdrawn')


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0012_add_sitevisit_date'),
    ]

    operations = [
        migrations.RunPython(
            code=fix_withdrawn,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]

