# Generated by Django 3.1.2 on 2023-02-26 12:44

from django.db import migrations

def update_select_name(apps, schema_editor):
    """
    update label
    """
    Applications = apps.get_model('agencies', 'Applications')

    for self in Applications.objects.all():
        old_mtime = self.mtime
        self.selectName = f'A{self.id} {self.agency.shortname} ({self.submitDate.year} {self.type}, {self.review})'
        self.save()
        Applications.objects.filter(pk=self.pk).update(mtime=old_mtime)


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0013_fix_withdrawn'),
    ]

    operations = [
        migrations.RunPython(
            code=update_select_name,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]

