# Generated by Django 3.1.2 on 2021-10-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nameEmail',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='person',
        ),
        migrations.RemoveField(
            model_name='octopusaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='alt_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='name',
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS new_octopusAccount;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS update_octopusAccount;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS new_agency_post;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS update_agency_post;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS update_organisation;"
        ),
    ]
