# Generated by Django 3.1.2 on 2021-11-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_drop_virtual_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='prefLang',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
