# Generated by Django 3.1.2 on 2022-04-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactorganisation',
            name='onRegister',
            field=models.BooleanField(db_column='onRegister', default=False, verbose_name='on Register entry?'),
        ),
    ]
