# Generated by Django 3.1.2 on 2022-05-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contactorganisation_onregister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['firstName', 'lastName'], 'verbose_name': 'person'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name']},
        ),
    ]
